// generated by compile -asmhdr from package argon2

#define const_Version 19
#define const_argon2d 0
#define const_argon2i 1
#define const_argon2id 2
#define const_blockLength 128
#define const_syncPoints 4
