// generated by compile -asmhdr from package crc64nvme

#define const_Size 8
#define const_NVME 11127430586519243189
#define digest__size 8
#define digest_crc 0
#define const_magic "crc\x02"
#define const_marshaledSize 20
#define const_tableSum 10222501432367280483
