// generated by compile -asmhdr from package cpu

#define littleEndian__size 0
#define bigEndian__size 0
#define CacheLinePad__size 64
#define option__size 32
#define option_Name 0
#define option_Feature 16
#define option_Specified 24
#define option_Enable 25
#define option_Required 26
#define const__PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE 30
#define const__PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE 31
#define const__PF_ARM_V81_ATOMIC_INSTRUCTIONS_AVAILABLE 34
#define const__PF_ARM_V82_DP_INSTRUCTIONS_AVAILABLE 43
#define const__PF_ARM_V83_JSCVT_INSTRUCTIONS_AVAILABLE 44
#define const__PF_ARM_V83_LRCPC_INSTRUCTIONS_AVAILABLE 45
#define const__PF_ARM_SVE_INSTRUCTIONS_AVAILABLE 46
#define const__PF_ARM_SVE2_INSTRUCTIONS_AVAILABLE 47
#define const__PF_ARM_SHA3_INSTRUCTIONS_AVAILABLE 64
#define const__PF_ARM_SHA512_INSTRUCTIONS_AVAILABLE 65
#define const_cacheLineSize 64
#define const_IsBigEndian false
#define const_errnoERROR_IO_PENDING 997
